-- For uploading dataset
USE ROLE ACCOUNTADMIN; 
CREATE OR REPLACE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA RETAIL_DB.ABT_BUY; 
USE DATABASE RETAIL_DB; 
USE SCHEMA ABT_BUY;

CREATE OR REPLACE TABLE ABT_BUY_PERFECTMAPPING ( 
    IDABT INTEGER NOT NULL, 
    IDBUY INTEGER NOT NULL, 
    CONSTRAINT pk_mapping PRIMARY KEY (IDABT, IDBUY) 
);

CREATE OR REPLACE TABLE ABT ( 
    ID INTEGER NOT NULL, 
    NAME VARCHAR(500), 
    DESCRIPTION VARCHAR(2000), 
    PRICE VARCHAR(50), 
    CONSTRAINT pk_abt_id PRIMARY KEY (ID) 
);

CREATE OR REPLACE TABLE BUY ( 
    ID INTEGER NOT NULL, 
    NAME VARCHAR(500), 
    DESCRIPTION VARCHAR(2000), 
    MANUFACTURER VARCHAR(200), 
    PRICE VARCHAR(50), 
    CONSTRAINT pk_buy_id PRIMARY KEY (ID) 
);